services:
  - type: web
    name: sanctuary-api
    env: python
    region: ohio # Customize to your preferred region (e.g., frankfurt, oregon, etc.)
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: ENVIRONMENT
        value: production
      - key: MONGODB_URI
        sync: false # Set in the Render dashboard manually
      - key: TMDB_API_KEY
        sync: false # Set in the Render dashboard manually
      - key: TMDB_READ_TOKEN
        sync: false
      - key: OMDB_API_KEY
        sync: false # Set in the Render dashboard manually
